config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end
  resources :post_questions, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :answers, only: [:create, :update, :destroy]
  end
  resources :post_movies, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :movie_likes, only: [:create, :destroy]
    resource :movie_comments, only: [:create, :update, :destroy]
  end
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :image_comments, only: [:create, :update, :destroy]
  end
  resources :notifications, only: [:index]
  get 'category/:id/post_images' => 'categories#index'
end

app/controllers/post_movies_controller.rb
class PostMoviesController < ApplicationController
  def new
  	 @post_movie = PostMovie.new
  end

  def index
  	 @post_movies = PostMovie.page(params[:page]).reverse_order.per(6)
  end

  def show
  	  @post_movie = PostMovie.find(params[:id])
  	  @movie_comment = MovieComment.new
  end

  def create
     @post_movie = PostMovie.new(post_movie_params)
     @post_movie.user_id = current_user.id
        if @post_movie.save(post_movie_params) && @post_movie.video.recreate_versions!
              redirect_to post_movie_path(@post_movie), notice: 'Article was successfully updated.'
        else
           render action: 'new'
        end
  end

  def edit
  	 @post_movie = PostMovie.find(params[:id])
  end

  def update
      post_movie = PostMovie.find(params[:id])
      post_movie.update(post_movie_params)
         redirect_to post_movie_path(post_movie)
  end

  def destroy
  	  @post_movie = PostMovie.find(params[:id])
      @post_movie.destroy
         redirect_to user_path(current_user)
  end

  private
  def post_movie_params
    params.require(:post_movie).permit(:title, :video, :caption)
  end

end

app/helpers/post_movies_helper.rb
module PostMoviesHelper
end

app/views/post_movies/edit.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>編集フォーム</span>
              </h3>
            </div>

                <%= form_for(@post_movie, url: post_movie_path) do |f| %>
                  <% if @post_movie.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= @post_movie.errors.count %>件のエラーが発生しました。</h2>
                        <ul>
                          <% @post_movie.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="row">
                  <div class="col-sm-12">
                    <%= f.file_field :video, :accept => 'video/*' %>
                  </div>
                </div>
                <br>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group has-icon">
                      <label class="control-label sr-only">タイトル</label>
                        <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
                         <span aria-hidden="true"></span>
                    </div>
                  </div>
                  <div class="col-sm-6">
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
                  </div>
                </div>
                <hr>
                <%= f.submit "保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_movies/index.html.erb
	<div class="container">
		<div class="row">
      <h3>動画投稿一覧</h3>
			<div class="post_movies" style="text-align: center; margin-left: 20px;">
			  <div class="movie-list jscroll">
      			<% @post_movies.each do |movie| %>
        			<ul class="list-group col-lg-3" style="width: 380px;">
  						<li class="list-group-item">
  							<div class="post-movies">
                  <%= link_to movie.video_url.to_s do %>
                   <i class="fa fa-play-circle"></i>
                    <%= image_tag(movie.video_url(:screenshot).to_s, id: "video", :alt => "screenshot", style: "height:13em;") %>
                    <% end %>
                </div>
              </li>
              <li class="list-group-item"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= movie.movie_likes.count %>
                  <span class="glyphicon glyphicon-comment" aria-hidden="true"><%= movie.movie_comments.count %></span>
                  <i class="fa fa-user"></i>
                              <%= link_to movie.user.name,user_path(movie.user.id) %></li>
              <li class="list-group-item"><%= link_to "詳細", post_movie_path(movie.id) %></li>
					</ul>
        		<% end %>
        	     <%= paginate @post_movies, class: "paginate" %>
        	  </div>
        	</div>
		</div>
	</div>

<script>
$(function() {
    $('.jscroll').jscroll({
    	contentSelector: '.movie-list',
      nextSelector: 'span.next:last a'
    });
});
</script>

app/views/post_movies/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>動画投稿フォーム</span>
              </h3>
            </div>

                <%= form_for(@post_movie, url: post_movies_path) do |f| %>
                  <% if @post_movie.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= @post_movie.errors.count %>件のエラーが発生しました。</h2>
                        <ul>
                          <% @post_movie.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="row">
                  <div class="col-sm-12">
                    <%= f.file_field :video, :accept => 'video/*' %>
                  </div>
                </div>
                <br>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group has-icon">
                      <label class="control-label sr-only">タイトル</label>
                        <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
                         <span aria-hidden="true"></span>
                    </div>
                  </div>
                  <div class="col-sm-6">
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
                  </div>
                </div>
                
                <hr>
                <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_movies/show.html.erb
<section class="sct-color-1 slice">
  <div class="container">
    <div class="row">
      <div class="col-md-12 post_movies_container">
        <div class="post-item">
          <div class="post-meta-top">
            <div class="post-movie">
                <br>
                <div class="col-xs-6 col-xs-offset-2">
                 <div class="post-movies">
     	             <%= link_to @post_movie.video_url.to_s do %>
                    <i class="fa fa-play-circle"></i>
                      <%= image_tag(@post_movie.video_url(:screenshot).to_s, id: "video", :alt => "screenshot", style: "height:300px;") %>
                   <% end %>
                 </div>
                </div>
              </div>
            </div>

         <div class="col-xs-4">
          <div class="post-content">
            <ul class="list-group col-lg-3" style="width: 300px;">
              <li class="list-group-item">
                <i class="fa fa-calendar"><%= @post_movie.created_at.strftime('%Y/%m/%d/%H:%M') %></i>
                <%= link_to user_path(@post_movie.user.id) do %>
                   <%= attachment_image_tag @post_movie.user, :profile_image, class: "img-circle profile-img", fallback: "no-image.jpg", size: "30x30" %>
                <% end %>
                <%= link_to @post_movie.user.name,user_path(@post_movie.user.id) %>
              </li>
              <% if user_signed_in? %>
                <!-- いいね -->
                <% if @post_movie.movie_liked_by?(current_user) %>
                  <li class="list-group-item">
                   <%= link_to post_movie_movie_likes_path(@post_movie), method: :delete do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                    <%= @post_movie.movie_likes.count %> いいね取消
                   <% end %>
                  </li>
                <% else %>

                  <li class="list-group-item">
                   <%= link_to post_movie_movie_likes_path(@post_movie), method: :post do %>
                   <i class="fa fa-heart-o" aria-hidden="true"></i>
                   <%= @post_movie.movie_likes.count %> いいね
                   <% end %>

                  </li>
                <% end %>
              <% end %>
                <!-- 編集/削除 -->
                <% if @post_movie.user == current_user %>
                  <li class="list-group-item">
                    <%= link_to "編集する", edit_post_movie_path(@post_movie) %>/
                    <%= link_to "削除する", post_movie_path(@post_movie), data: { confirm: "削除します。宜しいですか?" }, method: :delete %>
                  </li>
                <% end %>

                <li class="list-group-item">
                    <b>タイトル：</b><%= @post_movie.title %>
                </li>
                <li class="list-group-item">
                    <p><%= simple_format(@post_movie.caption) %></p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>

 <!-- コメントの表示 -->
    <div class="container">
      <div class="row-movie-comment">
        <br>
        <p><b class="comment-count">(<%= @post_movie.movie_comments.count %>件のコメント)</b></p>
               <% @post_movie.movie_comments.each do |movie_comment| %>
                  <div class="col-sm-2">
                    <div class="thumbnail">
                      <%= link_to user_path(movie_comment.user.id) do %>
                        <%= attachment_image_tag movie_comment.user, :profile_image, class: "img-circle profile-img", fallback: "no-image.jpg", size: "50x70" %>
                      <% end %>
                    </div>
                  </div>
                   <div class="col-sm-10">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <strong><%= link_to movie_comment.user.name,user_path(movie_comment.user.id) %></strong>
                          <span class="comment-date"><%= movie_comment.created_at.strftime('%Y/%m/%d/%H:%M') %></span>
                              <% if movie_comment.user == current_user %>
                                <%= link_to "削除する", post_movie_movie_comments_path(id: movie_comment,post_movie_id: @post_movie), method: :delete, "data-confirm" => "コメントを削除します。宜しいですか？" %>
                              <% end %>
                        </div>
                       <div class="panel-body"><%= movie_comment.comment %></div>
                      </div>
                    </div>
                <% end %>

           <!-- コメント投稿フォーム -->
           <div class="col-sm-12">
             <br>
             <div><h3>コメント</h3></div>
               <%= form_for [@post_movie, @movie_comment] do |f| %>
                 <div class="row">
                  <div class="col-sm-12">
                    <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                  </div>
                 </div>
                <%= f.submit "投稿する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
               <% end %>
           </div>
       </div>
    </div>
</section>