config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end
  resources :post_questions, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :answers, only: [:create, :update, :destroy]
  end
  resources :post_movies, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :movie_likes, only: [:create, :destroy]
    resource :movie_comments, only: [:create, :update, :destroy]
  end
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :image_comments, only: [:create, :update, :destroy]
  end
  resources :notifications, only: [:index]
  get 'category/:id/post_images' => 'categories#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_movies, dependent: :destroy
  has_many :post_questions, dependent: :destroy
  has_many :image_comments, dependent: :destroy
  has_many :movie_comments, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :movie_likes, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_many :notifications,dependent: :destroy

  # ユーザーに未確認の通知があるか確認
  def uncheck_notifications?
    self.passive_notifications.where(check: false).exists?
  end

  # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def create_notification_by(user)
    notification = user.active_notifications.new(
          follower_id: user.id,
          visited_id: self.id,
          action: "follow"
        )
    notification.save if notification.valid?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit,:update,:follows,:followers]

  def show
  	 @user = User.find(params[:id])
     @users = @user.followings
  end

  def edit
  	 @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
     @user.update(user_params)
      redirect_to user_path(@user.id)
  end

  def follows
     @user = User.find(params[:id])
     @users = @user.followings
  end

  def followers
     @user = User.find(params[:id])
     @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1"> 
                            <div class="form-header text-center">
                                <h2 class="form-header-title">プロフィール編集</h2>
                            </div>

                            <div class="form-body">
                              <%= form_for(@user) do |f| %>
                                <div class="form-group has-icon">
                                  <label class="control-label sr-only" for="inputName">Name</label>
                                   お名前(ニックネーム)
                                   <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"ニックネーム"%>
                                </div>
                            <div class="form-group has-icon">
                              <div class="user-edit-image">
                                <%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-img", fallback: "no-image.jpg", size: "120x120" %>
                              </div>
                                 <label class="control-label sr-only" for="user_profile_image">ProfileImage</label>
                                   <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                                     <div class="form-group has-icon">
                                         <br>
                                         自己紹介
                                         <%= f.text_area :introduction, rows:'5', class: "form-control",placeholder: "自己紹介をここに" %>
                                     </div>
                            </div>
                                   <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                                   <% end %>
                            </div>
                          </div>
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
       <div class="row-follow">
          <div class="form-header text-center">
             <h3 class="form-header-title">フォローされているユーザー</h3>
             <div class="form-body">
                <div class="row">
              　　　<% @users.each do |user| %>
                        <p><%= link_to user_path(user.id) do %>
                			<%= attachment_image_tag user, :profile_image, class: "img-circle profile-img", fallback: "no-image.jpg", size: "50x50" %>
                           <% end %>
                		   <%= link_to user.name,user_path(user.id) %>
                		   <% if current_user != user %>
                			 <% if user.followed_by?(current_user) %>
                			   <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class:"btn btn-default", :style=>"width: 120px;" %>
                			 <% else %>
                			   <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-primary", :style=>"width: 120px;" %>
                			 <% end %>
            			    <% end %>
                        </p>
            		<% end %>
	            </div>
             </div>
          </div>
       </div>
</div>

app/views/users/follows.html.erb
<div class="container">
     <div class="row-follow">
           <div class="form-header text-center">
                <h3 class="form-header-title">フォロー中のユーザー</h3>
                    <div class="form-body">
                       <div class="row">
  　　　　　　　　　　　　　　 <% @users.each do |user| %>
                              <p><%= link_to user_path(user.id) do %>
						       <%= attachment_image_tag user, :profile_image, class: "img-circle profile-img", fallback: "no-image.jpg", size: "50x50" %>
                              <% end %>
						     <%= link_to user.name,user_path(user.id) %>
						       <% if current_user != user %>
						          <% if user.followed_by?(current_user) %>
						             <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class:"btn btn-default", :style=>"width: 120px;" %>
						          <% else %>
						             <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-primary", :style=>"width: 120px;" %>
						          <% end %>
						       <% end %>
                              </p>
						     <% end %>
                       </div>
                    </div>
           </div>
     </div>
</div>

app/views/users/show.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-4 col-md-offset-4">
         <div class="form-user style-1 rounded has-shadow-1">
            <div class="form-header text-center">
               <h3 class="profile-name">
                 <p><%= @user.name %>
                  <% if user_signed_in? %>
                   <% if current_user != @user %>
                     <% if @user.followed_by?(current_user) %>
                       <%=link_to "フォロー解除", user_relationships_path(@user.id), method: :delete, class:"btn btn-default", :style=>"width: 120px;" %>
                     <% else %>
                       <%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-primary", :style=>"width: 120px;" %>
                     <% end %>
                   <% end %>
                  <% end %>
                 </p>
               </h3>
                 <p><%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-img", fallback: "no-image.jpg", size: "150x150" %></p>
                 <% if user_signed_in? %>
                   <p><%=link_to "フォロー", follows_user_path(@user.id) %><%= @user.followings.count %>人 / <%=link_to "フォロワー", followers_user_path(@user.id) %><%= @user.followers.count %>人</p>
                 <% else %>
                   <p><%=link_to "フォロー", follows_user_path(@user.id) %><%= @user.followings.count %>人 / <%=link_to "フォロワー", followers_user_path(@user.id) %><%= @user.followers.count %>人</p>
                 <% end %>
                 <p><%= simple_format(@user.introduction) %></p>
                 <% if user_signed_in? %>
                   <% if @user.id == current_user.id %>
                     <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-warning", :style=>"width: 200px;" %></p>
                   <% end %>
                 <% end %>
            </div>
         </div>
      </div>
   </div>
</div>
<br>
<div class="container">
  <div class="row">
    <ul class="tab">
        <li class="active">
            <span class="glyphicon glyphicon-picture" aria-hidden="true"> 写真</span></li>
        <li><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"> 動画</span></li>
        <% if @user == current_user %>
        <li><span class="glyphicon glyphicon-comment" aria-hidden="true"> 質問</span></li>
        <li><span class="glyphicon glyphicon-picture" aria-hidden="true"> フォロー中</span></li>
        <li><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"> フォロー中</span></li>
       <% end %>
    </ul>

      <div class="tabContent active">
            <h3 class="title">投稿写真一覧</h3>
                 <div class="post_images" style="text-align: center; margin-left: 20px;">
                  <% @user.post_images.reverse_order.each do |image| %>
                      <div class="col-lg-3" style="width: 280px;">
                      <%= link_to post_image_path(image.id) do %>
                         <%= attachment_image_tag image, :image, class: "profile-thumb", size: "220x220" %>
                      <% end %>
                        <p><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= image.likes.count %>
                          <span class="glyphicon glyphicon-comment" aria-hidden="true"><%= image.image_comments.count %></span>
                          <%= "(#{time_ago_in_words(image.created_at)}前)" %>
                        </p>
                      </div>
                  <% end %>
                 </div>
      </div>

      <div class="tabContent">
            <h3 class="title">投稿動画一覧</h3>
               <div class="post_movies" style="text-align: center; margin-left: 20px;">
                  <% @user.post_movies.reverse_order.each do |movie| %>
                   <ul class="list-group col-lg-3" style="width: 380px;">
                     <li class="list-group-item">
                       <div class="post-movies">
                        <%= link_to movie.video_url.to_s do %>
                          <i class="fa fa-play-circle"></i>
                           <%= image_tag(movie.video_url(:screenshot).to_s, id: "video", :alt => "screenshot", style: "height:13em;") %>
                        <% end %>
                       </div>
                     </li>
                       <li class="list-group-item"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                           <%= movie.movie_likes.count %>
                       <span class="glyphicon glyphicon-comment" aria-hidden="true">
                           <%= movie.movie_comments.count %></span>
                       <i class="fa fa-user"></i>
                           <%= link_to movie.user.name,user_path(movie.user.id) %></li>
                     <li class="list-group-item"><%= link_to "詳細", post_movie_path(movie.id) %><%= "(#{time_ago_in_words(movie.created_at)}前)" %></li>
                    </ul>
                  <% end %>
               </div>
      </div>

      <div class="tabContent">
            <h3 class="title">質問一覧</h3>
               <div class="post_questions" style="text-align: center; margin-left: 20px;">
                 <% @user.post_questions.reverse_order.each do |question| %>
                   <ul class="list-group col-lg-3" style="width: 380px;">
                      <li class="list-group-item list-group-item-warning"><b>タイトル：</b><%= link_to question.title, post_question_path(question.id) %></li>
            <li class="list-group-item" style="text-align: center;"><%= question.answers.count %>件の回答</li>
            <li class="list-group-item" style="text-align: center;"><%= question.created_at.strftime('%Y/%m/%d') %></li>
                   </ul>
                 <% end %>
               </div>
      </div>

      <div class="tabContent">
            <h3 class="title">フォローしているユーザーの投稿写真一覧</h3>
                 <div class="post_images" style="text-align: center; margin-left: 20px;">
                  <% @users.each do |user| %>
                    <% user.post_images.reverse_order.each do |image| %>
                       <div class="col-lg-3" style="width: 280px;">
                        <%= link_to post_image_path(image.id) do %>
                           <%= attachment_image_tag image, :image, class: "profile-thumb", size: "220x220" %>
                        <% end %>
                          <p><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= image.likes.count %>
                             <span class="glyphicon glyphicon-comment" aria-hidden="true"><%= image.image_comments.count %></span>
                             <i class="fa fa-user"></i>
                             <%= link_to image.user.name,user_path(image.user.id) %>
                            <%= "(#{time_ago_in_words(image.created_at)}前)" %>
                          </p>
                       </div>
                    <% end %>
                  <% end %>
                 </div>
      </div>
      <div class="tabContent">
            <h3 class="title">フォローしているユーザーの投稿動画一覧</h3>
                 <div class="post_movies" style="text-align: center; margin-left: 20px;">
                  <% @users.each do |user| %>
                   <% user.post_movies.reverse_order.each do |movie| %>
                     <ul class="list-group col-lg-3" style="width: 380px;">
                       <li class="list-group-item">
                          <%= link_to movie.video_url.to_s do %>
                             <%= image_tag(movie.video_url(:screenshot).to_s, id: "video", :alt => "screenshot", style: "height:13em;") %>
                          <% end %>
                       </li>
                         <li class="list-group-item"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                             <%= movie.movie_likes.count %>
                         <span class="glyphicon glyphicon-comment" aria-hidden="true">
                             <%= movie.movie_comments.count %></span>
                         <i class="fa fa-user"></i>
                             <%= link_to movie.user.name,user_path(movie.user.id) %></li>
                       <li class="list-group-item"><%= link_to "詳細", post_movie_path(movie.id) %><%= "(#{time_ago_in_words(movie.created_at)}前)" %></li>
                      </ul>
                    <% end %>
                  <% end %>
                 </div>
      </div>

   </div>
</div>

<script>
$(function() {
    $(".tab li").click(function() { //タブをクリックしたときのファンクションをまとめて指定
        var num = $(".tab li").index(this); //.index()を使いクリックされたタブが何番目かを調べ、numという変数に代入

        $(".tabContent").removeClass('active'); //コンテンツを一度すべて非表示

        $(".tabContent").eq(num).addClass('active'); //クリックされたタブと同じ順番のコンテンツを.activeをクラスに追加して表示

        $(".tab li").removeClass('active'); //一度タブについているクラス.activeを消して

        $(this).addClass('active') //クリックされたタブのみにクラス.activeをつける
    });
});
</script>