config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end
  resources :post_questions, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :answers, only: [:create, :update, :destroy]
  end
  resources :post_movies, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :movie_likes, only: [:create, :destroy]
    resource :movie_comments, only: [:create, :update, :destroy]
  end
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :image_comments, only: [:create, :update, :destroy]
  end
  resources :notifications, only: [:index]
  get 'category/:id/post_images' => 'categories#index'
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :post_image_category_relations
    has_many :categories, through: :post_image_category_relations
    has_many :image_comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :notifications,dependent: :destroy

    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end

    def create_notification_by(user)
        notification = user.active_notifications.new(
          post_image_id: self.id,
          visited_id: self.user.id,
          action: "like"
        )
        notification.save if notification.valid?
    end
    def create_notifications_by(user)
        notification = user.active_notifications.new(
          post_image_id: self.id,
          visited_id: self.user.id,
          action: "image_comment"
        )
        notification.save if notification.valid?
    end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
  	  @post_image = PostImage.new
  end

  def index
  	  @post_images = PostImage.page(params[:page]).reverse_order.per(9)
      @all_ranks = PostImage.find(Like.group(:post_image_id).order('count(post_image_id) desc').limit(3).pluck(:post_image_id))
      @categories = Category.all
  end

  def show
  	  @post_image = PostImage.find(params[:id])
  	  @image_comment = ImageComment.new
      @categories = Category.all
  end

  def create
  	  @post_image = PostImage.new(post_image_params)
        @post_image.user_id = current_user.id
        if @post_image.save
          redirect_to post_image_path(@post_image)
        else
          render :new
        end
  end

  def edit
      @post_image = PostImage.find(params[:id])
  end

  def update
      post_image = PostImage.find(params[:id])
      post_image.update(post_image_params)
         redirect_to post_image_path(post_image)
  end

  def destroy
  	  @post_image = PostImage.find(params[:id])
      @post_image.destroy
         redirect_to user_path(current_user)
  end

  private
    def post_image_params
        params.require(:post_image).permit(:title, :image, :caption, category_ids: [])
    end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/edit.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>編集画面</span>
              </h3>
            </div>

          <%= form_for(@post_image, url: post_image_path) do |f| %>
            <% if @post_image.errors.any? %>
              <div id="error_explanation">
                <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
                <ul>
                <% @post_image.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
               </div>
              <% end %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">タイトル</label>
                    <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
                    <span aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                 <%= f.label :category, 'カテゴリー' %>
                   <%= f.collection_check_boxes(:category_ids, Category.all, :id, :category_name) do |category| %> 
                   <%= category.label do %>
                   <%= category.check_box %>
                   <%= category.text %>
                   <% end %>
                 <% end %>
                </div>
              </div>

              <hr>
              <%= f.submit "保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_images/index.html.erb
<body>
	<div class="container">
		<div class="row">
		  <div class="col-lg-2">
			<div class="box">
               <span class="box-title">カテゴリ別</span>
				  <% @categories.each do |category| %>
					 <ul>
				        <li><%= link_to category.category_name,'/category/'+category.id.to_s+'/post_images' %></li>
					 </ul>
				  <% end %>
            </div>
          </div>
         <div class="col-lg-10">
          <h3>人気投稿</h3>
			<div class="post_images" style="text-align: center; margin-left: 25px;">
			  <% @all_ranks.each do |image| %>
        	      <div class="col-lg-3" style="width: 300px;">
				     	 <%= link_to post_image_path(image.id) do %>
				     	   <%= attachment_image_tag image, :image, class: "profile-thumb", size: "250x250" %>
				     	 <% end %>
				     	<p><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= image.likes.count %>
				     		<span class="glyphicon glyphicon-comment" aria-hidden="true"><%= image.image_comments.count %></span>
				     		<i class="fa fa-user"></i>
                            <%= link_to image.user.name,user_path(image.user.id) %>
				     	</p>
				  </div>
        	  <% end %>
            </div>
          <div>
           <h3>投稿写真一覧(新着順)</h3>
			 <div class="post_images" style="text-align: center; margin-left: 25px;">
			  <div class="image-list jscroll">
      			<% @post_images.each do |image| %>
        			<div class="col-lg-3" style="width: 300px;">
				     	 <%= link_to post_image_path(image.id) do %>
				     	   <%= attachment_image_tag image, :image, class: "profile-thumb", size: "250x250" %>
				     	 <% end %>
				     	<p><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= image.likes.count %>
				     		<span class="glyphicon glyphicon-comment" aria-hidden="true"><%= image.image_comments.count %></span>
				     		<i class="fa fa-user"></i>
                            <%= link_to image.user.name,user_path(image.user.id) %>
				     	</p>
					</div>
        		<% end %>
        		<%= paginate @post_images, class: "paginate" %>
              </div>
             </div>
         </div>
		</div>
	</div>
  </div>
</body>

<script>
$(window).on('scroll', function() {
    scrollHeight = $(document).height();
    scrollPosition = $(window).height() + $(window).scrollTop();
    if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
		    $('.jscroll').jscroll({
		    	contentSelector: '.image-list',
		      nextSelector: 'span.next:last a'
            });
	}
});
</script>

app/views/post_images/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>写真投稿フォーム</span>
              </h3>
            </div>

          <%= form_for(@post_image, url: post_images_path) do |f| %>
            <% if @post_image.errors.any? %>
              <div id="error_explanation">
                <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
                <ul>
                <% @post_image.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
               </div>
              <% end %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">タイトル</label>
                    <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
                    <span aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                 <%= f.label :category, 'カテゴリー' %><br>
                   <%= f.collection_check_boxes(:category_ids, Category.all, :id, :category_name) do |category| %> 
                   <%= category.label do %>
                   <%= category.check_box %>
                   <%= category.text %>
                   <% end %>
                 <% end %>
                </div>
              </div>

              <hr>
              <%= f.submit "投稿", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_images/show.html.erb
<section class="sct-color-1 slice">
  <div class="container">
    <div class="row">
      <div class="col-md-12 post_images_container">
        <div class="post-item">
          <div class="post-meta-top">
            <div class="post-image">
              <br>
              <div class="col-xs-5 col-xs-offset-2">
                <%= attachment_image_tag @post_image, :image, class: "profile-thumb", size: "400x400" %>
              </div>
            </div>
          </div>

          <div class="col-xs-5">
            <div class="post-content">

              <ul class="list-group col-lg-3" style="width: 300px;">
                <li class="list-group-item">
                  <i class="fa fa-calendar"><%= @post_image.created_at.strftime('%Y/%m/%d/%H:%M') %></i>
                     <%= link_to user_path(@post_image.user.id) do %>
                       <%= attachment_image_tag @post_image.user, :profile_image, class: "img-circle profile-img", fallback: "no-image.jpg", size: "30x30" %>
                     <% end %>
                     <%= link_to @post_image.user.name,user_path(@post_image.user.id) %>
                </li>
                <li class="list-group-item">
                  <b>カテゴリー：</b>
                  <% @post_image.categories.each do |category| %>
                    <%= link_to category.category_name,'/category/'+category.id.to_s+'/post_images' %>
                  <% end %>
                </li>

                <% if user_signed_in? %>
                  <!-- いいね -->
                  <% if @post_image.liked_by?(current_user) %>

                    <li class="list-group-item">
                     <%= link_to post_image_likes_path(@post_image), method: :delete do %>
                      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= @post_image.likes.count %> いいね取消
                     <% end %>
                    </li>
                  <% else %>

                   <li class="list-group-item">
                     <%= link_to post_image_likes_path(@post_image), method: :post do %>
                      <i class="fa fa-heart-o" aria-hidden="true"></i>
                      <%= @post_image.likes.count %> いいね
                     <% end %>
                   </li>
                  <% end %>
                <% end %>
                  <!-- 編集/削除 -->
                  <% if @post_image.user == current_user %>
                   <li class="list-group-item">
                     <%= link_to "編集する", edit_post_image_path(@post_image) %>/
                     <%= link_to "削除する", post_image_path(@post_image), data: { confirm: "投稿を削除します。宜しいですか?" }, method: :delete %>
                   </li>
                  <% end %>
                  <li class="list-group-item">
                    <b>タイトル：</b><%= @post_image.title %>
                  </li>
                  <li class="list-group-item">
                    <p><%= simple_format(@post_image.caption) %></p>
                  </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- コメントの表示 -->
  <div class="container">
    <div class="row-comment">
      <br>
      <p><b class="comment-count">(<%= @post_image.image_comments.count %>件のコメント)</b></p>
      <% @post_image.image_comments.each do |image_comment| %>
        <div class="col-sm-2">
          <div class="thumbnail">
            <%= link_to user_path(image_comment.user.id) do %>
              <%= attachment_image_tag image_comment.user, :profile_image, class: "img-circle profile-img", fallback: "no-image.jpg", size: "50x70" %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <strong><%= link_to image_comment.user.name,user_path(image_comment.user.id) %></strong>
              <span><%= image_comment.created_at.strftime('%Y/%m/%d/%H:%M') %></span>
              <% if image_comment.user == current_user %>
                <%= link_to "削除する", post_image_image_comments_path(id: image_comment,post_image_id: @post_image), method: :delete, "data-confirm" => "コメントを削除します。宜しいですか？" %>
              <% end %>
            </div>
            <div class="panel-body"><%= image_comment.comment %></div>
          </div>
        </div>
      <% end %>
      <!-- コメント投稿フォーム -->
      <div class="col-sm-12">
        <br>
        <div><h3>コメント</h3></div>
        <%= form_for [@post_image, @image_comment] do |f| %>
          <div class="row">
            <div class="col-sm-12">
              <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
            </div>
          </div>
          <%= f.submit "投稿する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</section>