config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end
  resources :post_questions, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :answers, only: [:create, :update, :destroy]
  end
  resources :post_movies, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :movie_likes, only: [:create, :destroy]
    resource :movie_comments, only: [:create, :update, :destroy]
  end
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :image_comments, only: [:create, :update, :destroy]
  end
  resources :notifications, only: [:index]
  get 'category/:id/post_images' => 'categories#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
   belongs_to :user
   belongs_to :post_question
   has_many :notifications,dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :post_image_category_relations
    has_many :post_images, through: :post_image_category_relations
end

app/models/image_comment.rb
class ImageComment < ApplicationRecord
	belongs_to :user
    belongs_to :post_image
    has_many :notifications,dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
    belongs_to :post_image
end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
	belongs_to :user
    belongs_to :post_movie
    has_many :notifications,dependent: :destroy
end

app/models/movie_like.rb
class MovieLike < ApplicationRecord
    belongs_to :user
    belongs_to :post_movie
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}
  belongs_to :post_image, optional: true
  belongs_to :image_comment, optional: true
  belongs_to :post_movie, optional: true
  belongs_to :movie_comment, optional: true
  belongs_to :post_question, optional: true
  belongs_to :answer, optional: true
  belongs_to :user, optional: true


  # 通知送ってきた側のユーザーを取得
  def visiter
  	User.find_by(id: self.visiter_id)
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :post_image_category_relations
    has_many :categories, through: :post_image_category_relations
    has_many :image_comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :notifications,dependent: :destroy

    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end

    def create_notification_by(user)
        notification = user.active_notifications.new(
          post_image_id: self.id,
          visited_id: self.user.id,
          action: "like"
        )
        notification.save if notification.valid?
    end
    def create_notifications_by(user)
        notification = user.active_notifications.new(
          post_image_id: self.id,
          visited_id: self.user.id,
          action: "image_comment"
        )
        notification.save if notification.valid?
    end
end

app/models/post_movie.rb
class PostMovie < ApplicationRecord
	mount_uploader :video, VideoUploader
	validates :title, :caption, :video, :presence => true
	belongs_to :user
	has_many :movie_comments, dependent: :destroy
	has_many :movie_likes, dependent: :destroy
	has_many :notifications,dependent: :destroy

    def movie_liked_by?(user)
        movie_likes.where(user_id: user.id).exists?
    end

    def create_notification_by(user)
  	    notification = user.active_notifications.new(
  	      post_movie_id:self.id,
  	      visited_id:self.user.id,
  	      action:"movie_like"
  	    )
  	    notification.save if notification.valid?
    end
    def create_notifications_by(user)
        notification = user.active_notifications.new(
          post_movie_id: self.id,
          visited_id: self.user.id,
          action: "movie_comment"
        )
        notification.save if notification.valid?
    end
end

app/models/post_question.rb
class PostQuestion < ApplicationRecord
	belongs_to :user
	has_many :answers, dependent: :destroy
	has_many :notifications,dependent: :destroy

    def create_notification_by(user)
        notification = user.active_notifications.new(
          post_question_id: self.id,
          visited_id: self.user.id,
          action: "answer"
        )
        notification.save if notification.valid?
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_movies, dependent: :destroy
  has_many :post_questions, dependent: :destroy
  has_many :image_comments, dependent: :destroy
  has_many :movie_comments, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :movie_likes, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_many :notifications,dependent: :destroy

  # ユーザーに未確認の通知があるか確認
  def uncheck_notifications?
    self.passive_notifications.where(check: false).exists?
  end

  # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def create_notification_by(user)
    notification = user.active_notifications.new(
          follower_id: user.id,
          visited_id: self.id,
          action: "follow"
        )
    notification.save if notification.valid?
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  	  @post_images = PostImage.order(created_at: :desc).limit(4)
  	  @post_movies = PostMovie.order(created_at: :desc).limit(3)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SHIBAcafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!-- トップへ戻るボタン -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">
　　<div id="page_top"><a href="#"></a></div>

  <body>
   <div class="main-visual">
     <p>柴犬好きが集まる<br>
        コミュニティサイト<br>
        出来ました。
     </p>
     <header class="clearfix">
        <div class="container-fluid">
          <div class="container">
            <div class="row">
                <div class="col-sm-4">
                  <button type="button" class="navbar-toggle collapsed"data-toggle="collapse"data-target="#navbarEexample8">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>

                  <div class="navbar-brand">
                    <a href="/"><%= image_tag 'logologo.png', size:'200x55' %></a>
                  </div>
                </div>

                  <div class="clearfix col-sm-8">
                    <div class="collapse navbar-collapse"  id="navbarEexample8">
                      <div class="navbar-right">
                      <% if user_signed_in? %>
                      <br>
                      <ul class="nav navbar-nav" style="margin-top:5px;">
                        <li><a href="#">投稿する</a>
                          <ul>
                            <li><%= link_to "写真を投稿",new_post_image_path %></li>
                            <li><%= link_to "動画を投稿",new_post_movie_path %></li>
                            <li><%= link_to "質問を投稿",new_post_question_path %></li>
                          </ul>
                        </li>
                        <li><%= link_to "マイページ",user_path(current_user.id) %>
                          <ul>
                            <li><%= link_to "アカウント編集/退会",edit_user_registration_path(current_user.id) %></li>
                          </ul>
                        </li>
                        <li class="notification-item"><%= link_to '通知', notifications_path, class:"btn"  %>
                            <% if current_user.uncheck_notifications? %>
                               <!-- <i class="fa fa-circle notification-circle"> -->
                                <!-- </i> -->
                                <div class="circle">
                                <div class="notice-count">
                                   <%= current_user.passive_notifications.where(check: false).count %>
                                 </div>
                                </div>
                              <% end %>
                        </li>
                            
                        <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
                      </ul>
                      <% else %>
                       <br>
                        <ul class="nav navbar-nav" style="margin-top:5px;">
                          <li><%=link_to "新規会員登録", new_user_registration_path %></li>
                          <li><%=link_to "ログイン", new_user_session_path %></li>
                        </ul>
                      <% end %>
                     </div>
                    </div>
                  </div>
            </div>
          </div>
        </div>
    </header>
  </div>
             <div class="container">
                <div class="row">
                  <nav id="globalNavi">
                   <br>
                    <ul>
                      <li><%= link_to "写真を見る",post_images_path %></li>
                      <li><%= link_to "動画を見る",post_movies_path %></li>
                      <li><%= link_to "質問コーナー",post_questions_path %></li>
                    </ul>
                  </nav>
                </div>
             </div>

    <%= yield %>

  <footer class="footer style-2">
    <div class="container">
      <div class="row">
          <div class="footer-store-info col-lg-12" style="margin-top: 10px; text-align: center;">
            <p>CopyRight SHIBA CAFE.inc</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>

<script>
//トップへ戻るボタン
jQuery(function() {
  var appear = false;
  var pagetop = $('#page_top');
  $(window).scroll(function () {
    if ($(this).scrollTop() > 150) {  //100pxスクロールしたら
      if (appear == false) {
        appear = true;
        pagetop.stop().animate({
          'right': '50px' //右から0pxの位置に
        }, 300); //0.3秒かけて現れる
      }
    } else {
      if (appear) {
        appear = false;
        pagetop.stop().animate({
          'right': '-50px' //右から-50pxの位置に
        }, 300); //0.3秒かけて隠れる
      }
    }
  });
  pagetop.click(function () {
    $('body, html').animate({ scrollTop: 0 }, 500); //0.5秒かけてトップへ戻る
    return false;
  });
});

// ヘッダーナビ
$(function() {
var nav = $('.nav');
$('li', nav)
.mouseover(function(e) {
$('ul', this).stop().slideDown('fast');
})
.mouseout(function(e) {
$('ul', this).stop().slideUp('fast');
});
});
</script>